// <auto-generated />
using System;
using GoldPriceMonitorApi_DotNet.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldPriceMonitorApi_DotNet.Migrations
{
    [DbContext(typeof(GoldPriceDbContext))]
    [Migration("20240121131758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldPriceMonitorApi_DotNet.Database.BaoTinMinhChau", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<float>("GiaBanRa")
                        .HasColumnType("real");

                    b.Property<float>("GiaMuaVao")
                        .HasColumnType("real");

                    b.Property<float>("GiaTheGioi")
                        .HasColumnType("real");

                    b.Property<string>("HamLuongKara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HamLuongVang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BaoTinMinhChaus");
                });

            modelBuilder.Entity("GoldPriceMonitorApi_DotNet.Database.VangSjc", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<float>("BuyPrice")
                        .HasColumnType("real");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SellPrice")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VangSjcs");
                });
#pragma warning restore 612, 618
        }
    }
}
