// <auto-generated />
using System;
using DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MYSQL_Migrations.Migrations
{
    [DbContext(typeof(GoldPriceDbContext))]
    [Migration("20240430134801_InitialCreate_MYSQL")]
    partial class InitialCreate_MYSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DatabaseContext.BaoTinMinhChau", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<float>("GiaBanRa")
                        .HasColumnType("float");

                    b.Property<float>("GiaMuaVao")
                        .HasColumnType("float");

                    b.Property<float>("GiaTheGioi")
                        .HasColumnType("float");

                    b.Property<string>("HamLuongKara")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HamLuongVang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianNhap")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BaoTinMinhChaus");
                });

            modelBuilder.Entity("DatabaseContext.VangSjc", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<float>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("SellPrice")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VangSjcs");
                });
#pragma warning restore 612, 618
        }
    }
}
